/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.Trylof.services.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.sql.Blob;

import java.util.Date;

/**
 * The base model interface for the ItemFound service. Represents a row in the &quot;LofService_ItemFound&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.Trylof.services.model.impl.ItemFoundModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.Trylof.services.model.impl.ItemFoundImpl}.
 * </p>
 *
 * @author Utkarsh
 * @see ItemFound
 * @see com.Trylof.services.model.impl.ItemFoundImpl
 * @see com.Trylof.services.model.impl.ItemFoundModelImpl
 * @generated
 */
@ProviderType
public interface ItemFoundModel extends BaseModel<ItemFound> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a item found model instance should use the {@link ItemFound} interface instead.
	 */

	/**
	 * Returns the primary key of this item found.
	 *
	 * @return the primary key of this item found
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this item found.
	 *
	 * @param primaryKey the primary key of this item found
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the item found ID of this item found.
	 *
	 * @return the item found ID of this item found
	 */
	public long getItemFoundId();

	/**
	 * Sets the item found ID of this item found.
	 *
	 * @param itemFoundId the item found ID of this item found
	 */
	public void setItemFoundId(long itemFoundId);

	/**
	 * Returns the user ID of this item found.
	 *
	 * @return the user ID of this item found
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this item found.
	 *
	 * @param userId the user ID of this item found
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this item found.
	 *
	 * @return the user uuid of this item found
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this item found.
	 *
	 * @param userUuid the user uuid of this item found
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the found date of this item found.
	 *
	 * @return the found date of this item found
	 */
	public Date getFoundDate();

	/**
	 * Sets the found date of this item found.
	 *
	 * @param FoundDate the found date of this item found
	 */
	public void setFoundDate(Date FoundDate);

	/**
	 * Returns the found location of this item found.
	 *
	 * @return the found location of this item found
	 */
	@AutoEscape
	public String getFoundLocation();

	/**
	 * Sets the found location of this item found.
	 *
	 * @param FoundLocation the found location of this item found
	 */
	public void setFoundLocation(String FoundLocation);

	/**
	 * Returns the found company of this item found.
	 *
	 * @return the found company of this item found
	 */
	@AutoEscape
	public String getFoundCompany();

	/**
	 * Sets the found company of this item found.
	 *
	 * @param FoundCompany the found company of this item found
	 */
	public void setFoundCompany(String FoundCompany);

	/**
	 * Returns the found color of this item found.
	 *
	 * @return the found color of this item found
	 */
	@AutoEscape
	public String getFoundColor();

	/**
	 * Sets the found color of this item found.
	 *
	 * @param FoundColor the found color of this item found
	 */
	public void setFoundColor(String FoundColor);

	/**
	 * Returns the found size of this item found.
	 *
	 * @return the found size of this item found
	 */
	@AutoEscape
	public String getFoundSize();

	/**
	 * Sets the found size of this item found.
	 *
	 * @param FoundSize the found size of this item found
	 */
	public void setFoundSize(String FoundSize);

	/**
	 * Returns the found type of this item found.
	 *
	 * @return the found type of this item found
	 */
	@AutoEscape
	public String getFoundType();

	/**
	 * Sets the found type of this item found.
	 *
	 * @param FoundType the found type of this item found
	 */
	public void setFoundType(String FoundType);

	/**
	 * Returns the found status of this item found.
	 *
	 * @return the found status of this item found
	 */
	@AutoEscape
	public String getFoundStatus();

	/**
	 * Sets the found status of this item found.
	 *
	 * @param FoundStatus the found status of this item found
	 */
	public void setFoundStatus(String FoundStatus);

	/**
	 * Returns the found desc of this item found.
	 *
	 * @return the found desc of this item found
	 */
	@AutoEscape
	public String getFoundDesc();

	/**
	 * Sets the found desc of this item found.
	 *
	 * @param FoundDesc the found desc of this item found
	 */
	public void setFoundDesc(String FoundDesc);

	/**
	 * Returns the lost item of this item found.
	 *
	 * @return the lost item of this item found
	 */
	public long getLostItem();

	/**
	 * Sets the lost item of this item found.
	 *
	 * @param LostItem the lost item of this item found
	 */
	public void setLostItem(long LostItem);

	/**
	 * Returns the mime type of this item found.
	 *
	 * @return the mime type of this item found
	 */
	@AutoEscape
	public String getMimeType();

	/**
	 * Sets the mime type of this item found.
	 *
	 * @param mimeType the mime type of this item found
	 */
	public void setMimeType(String mimeType);

	/**
	 * Returns the blob data of this item found.
	 *
	 * @return the blob data of this item found
	 */
	public Blob getBlobData();

	/**
	 * Sets the blob data of this item found.
	 *
	 * @param blobData the blob data of this item found
	 */
	public void setBlobData(Blob blobData);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.Trylof.services.model.ItemFound itemFound);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.Trylof.services.model.ItemFound> toCacheModel();

	@Override
	public com.Trylof.services.model.ItemFound toEscapedModel();

	@Override
	public com.Trylof.services.model.ItemFound toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}