/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.Trylof.services.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.sql.Blob;

/**
 * The base model interface for the ItemVerification service. Represents a row in the &quot;LofService_ItemVerification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.Trylof.services.model.impl.ItemVerificationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.Trylof.services.model.impl.ItemVerificationImpl}.
 * </p>
 *
 * @author Utkarsh
 * @see ItemVerification
 * @see com.Trylof.services.model.impl.ItemVerificationImpl
 * @see com.Trylof.services.model.impl.ItemVerificationModelImpl
 * @generated
 */
@ProviderType
public interface ItemVerificationModel extends BaseModel<ItemVerification> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a item verification model instance should use the {@link ItemVerification} interface instead.
	 */

	/**
	 * Returns the primary key of this item verification.
	 *
	 * @return the primary key of this item verification
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this item verification.
	 *
	 * @param primaryKey the primary key of this item verification
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the item verification ID of this item verification.
	 *
	 * @return the item verification ID of this item verification
	 */
	public long getItemVerificationId();

	/**
	 * Sets the item verification ID of this item verification.
	 *
	 * @param itemVerificationId the item verification ID of this item verification
	 */
	public void setItemVerificationId(long itemVerificationId);

	/**
	 * Returns the verify desc of this item verification.
	 *
	 * @return the verify desc of this item verification
	 */
	@AutoEscape
	public String getVerifyDesc();

	/**
	 * Sets the verify desc of this item verification.
	 *
	 * @param VerifyDesc the verify desc of this item verification
	 */
	public void setVerifyDesc(String VerifyDesc);

	/**
	 * Returns the image1 of this item verification.
	 *
	 * @return the image1 of this item verification
	 */
	public Blob getImage1();

	/**
	 * Sets the image1 of this item verification.
	 *
	 * @param Image1 the image1 of this item verification
	 */
	public void setImage1(Blob Image1);

	/**
	 * Returns the image2 of this item verification.
	 *
	 * @return the image2 of this item verification
	 */
	public Blob getImage2();

	/**
	 * Sets the image2 of this item verification.
	 *
	 * @param Image2 the image2 of this item verification
	 */
	public void setImage2(Blob Image2);

	/**
	 * Returns the lost itemid of this item verification.
	 *
	 * @return the lost itemid of this item verification
	 */
	public long getLostItemid();

	/**
	 * Sets the lost itemid of this item verification.
	 *
	 * @param LostItemid the lost itemid of this item verification
	 */
	public void setLostItemid(long LostItemid);

	/**
	 * Returns the found itemid of this item verification.
	 *
	 * @return the found itemid of this item verification
	 */
	public long getFoundItemid();

	/**
	 * Sets the found itemid of this item verification.
	 *
	 * @param FoundItemid the found itemid of this item verification
	 */
	public void setFoundItemid(long FoundItemid);

	/**
	 * Returns the user ID of this item verification.
	 *
	 * @return the user ID of this item verification
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this item verification.
	 *
	 * @param UserId the user ID of this item verification
	 */
	public void setUserId(long UserId);

	/**
	 * Returns the user uuid of this item verification.
	 *
	 * @return the user uuid of this item verification
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this item verification.
	 *
	 * @param UserUuid the user uuid of this item verification
	 */
	public void setUserUuid(String UserUuid);

	/**
	 * Returns the verify status of this item verification.
	 *
	 * @return the verify status of this item verification
	 */
	@AutoEscape
	public String getVerifyStatus();

	/**
	 * Sets the verify status of this item verification.
	 *
	 * @param VerifyStatus the verify status of this item verification
	 */
	public void setVerifyStatus(String VerifyStatus);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.Trylof.services.model.ItemVerification itemVerification);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.Trylof.services.model.ItemVerification> toCacheModel();

	@Override
	public com.Trylof.services.model.ItemVerification toEscapedModel();

	@Override
	public com.Trylof.services.model.ItemVerification toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}