/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.Trylof.services.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the UserMaster service. Represents a row in the &quot;LofService_UserMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.Trylof.services.model.impl.UserMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.Trylof.services.model.impl.UserMasterImpl}.
 * </p>
 *
 * @author Utkarsh
 * @see UserMaster
 * @see com.Trylof.services.model.impl.UserMasterImpl
 * @see com.Trylof.services.model.impl.UserMasterModelImpl
 * @generated
 */
@ProviderType
public interface UserMasterModel extends BaseModel<UserMaster> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user master model instance should use the {@link UserMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this user master.
	 *
	 * @return the primary key of this user master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user master.
	 *
	 * @param primaryKey the primary key of this user master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user master ID of this user master.
	 *
	 * @return the user master ID of this user master
	 */
	public long getUserMasterId();

	/**
	 * Sets the user master ID of this user master.
	 *
	 * @param userMasterId the user master ID of this user master
	 */
	public void setUserMasterId(long userMasterId);

	/**
	 * Returns the user name of this user master.
	 *
	 * @return the user name of this user master
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this user master.
	 *
	 * @param userName the user name of this user master
	 */
	public void setUserName(String userName);

	/**
	 * Returns the user email of this user master.
	 *
	 * @return the user email of this user master
	 */
	@AutoEscape
	public String getUserEmail();

	/**
	 * Sets the user email of this user master.
	 *
	 * @param userEmail the user email of this user master
	 */
	public void setUserEmail(String userEmail);

	/**
	 * Returns the user pass of this user master.
	 *
	 * @return the user pass of this user master
	 */
	@AutoEscape
	public String getUserPass();

	/**
	 * Sets the user pass of this user master.
	 *
	 * @param userPass the user pass of this user master
	 */
	public void setUserPass(String userPass);

	/**
	 * Returns the user address of this user master.
	 *
	 * @return the user address of this user master
	 */
	@AutoEscape
	public String getUserAddress();

	/**
	 * Sets the user address of this user master.
	 *
	 * @param userAddress the user address of this user master
	 */
	public void setUserAddress(String userAddress);

	/**
	 * Returns the user phoneno of this user master.
	 *
	 * @return the user phoneno of this user master
	 */
	public int getUserPhoneno();

	/**
	 * Sets the user phoneno of this user master.
	 *
	 * @param userPhoneno the user phoneno of this user master
	 */
	public void setUserPhoneno(int userPhoneno);

	/**
	 * Returns the user type of this user master.
	 *
	 * @return the user type of this user master
	 */
	@AutoEscape
	public String getUserType();

	/**
	 * Sets the user type of this user master.
	 *
	 * @param userType the user type of this user master
	 */
	public void setUserType(String userType);

	/**
	 * Returns the user organization of this user master.
	 *
	 * @return the user organization of this user master
	 */
	@AutoEscape
	public String getUserOrganization();

	/**
	 * Sets the user organization of this user master.
	 *
	 * @param userOrganization the user organization of this user master
	 */
	public void setUserOrganization(String userOrganization);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.Trylof.services.model.UserMaster userMaster);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.Trylof.services.model.UserMaster> toCacheModel();

	@Override
	public com.Trylof.services.model.UserMaster toEscapedModel();

	@Override
	public com.Trylof.services.model.UserMaster toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}