/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.Trylof.services.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.Trylof.services.model.ItemVerification;
import com.Trylof.services.service.ItemVerificationLocalServiceUtil;

/**
 * The extended model base implementation for the ItemVerification service. Represents a row in the &quot;LofService_ItemVerification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ItemVerificationImpl}.
 * </p>
 *
 * @author Utkarsh
 * @see ItemVerificationImpl
 * @see ItemVerification
 * @generated
 */
@ProviderType
public abstract class ItemVerificationBaseImpl extends ItemVerificationModelImpl
	implements ItemVerification {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a item verification model instance should use the {@link ItemVerification} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ItemVerificationLocalServiceUtil.addItemVerification(this);
		}
		else {
			ItemVerificationLocalServiceUtil.updateItemVerification(this);
		}
	}
}